### ISSUE TITLE
ZZZ's Charge.exe's Check-in doesn't work.

### ISSUE THREAD

**Issue by Dragoonstorm1** [Beastwick18/genshin-real-time-notes#2]
I really appreciate the feature, makes me miss a lot less than the awful hoyolab. It works perfectly for Genshin's Resin.exe, but check-in does not get registered for ZZZ's Charge.exe.

That's basically it. Thank you so much for the apps!

**Comment by Beastwick18** [comment]
Yep thanks for pointing that out. It looks like the URL for sending check-in requests changed. I'll update it and push out a new release soon.

**Comment by Beastwick18** [comment]
Commit c7706df should fix it. I'll have to check if it works when the check-in resets tomorrow

**Comment by Beastwick18** [comment]
Confirmed working on d4429b6. Will push a new release soon with these changes
